sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm test
  - node src/npm-test.js
  # a few "e2e" tests
  - node src/repo-install.js
after_success:
  - npm run semantic-release
  - npm run coverage-codacy
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
